/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dxlR9faTtPh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { AlertDialogTrigger, AlertDialogTitle, AlertDialogDescription, AlertDialogHeader, AlertDialogCancel, AlertDialogFooter, AlertDialogContent, AlertDialog } from "@/components/ui/alert"

export function ErrorModal() {
  return (
    (<AlertDialog defaultOpen>
      <AlertDialogTrigger asChild>
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <Button variant="destructive">Show Error Modal</Button>
        </div>
      </AlertDialogTrigger>
      <AlertDialogContent
        className="w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
        <AlertDialogHeader>
          <AlertDialogTitle className="text-2xl font-bold">Error Creating Email</AlertDialogTitle>
          <AlertDialogDescription className="mt-2 text-gray-500 dark:text-gray-400">
            There was an issue sending your email. Please try again later.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter className="mt-4 flex justify-end">
          <AlertDialogCancel
            className="rounded-md bg-gray-100 px-4 py-2 text-gray-900 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 dark:bg-gray-700 dark:text-gray-100 dark:hover:bg-gray-600 dark:focus:ring-gray-600 dark:focus:ring-offset-gray-800">
            Close
          </AlertDialogCancel>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>)
  );
}
